[project]
name = "mvf-hack-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "groq>=0.26.0",
    "pydantic>=2.11.5",
    "python-dotenv>=1.1.0",
    "ruff>=0.11.13",
]
